### ISSUE TITLE
"iVersion update check failed because an unknown error occured"

### ISSUE THREAD

**Issue by Abhishaker17** [nicklockwood/iVersion#86]
Console logs this error every time I start my application. Any pointers why?

**Comment by Just-** [comment]
same issue, i found that iVersion use **nil** for **appStoreCountry** 
_iVersion is checking http://itunes.apple.com/(null)/lookup?bundleId=..._

appStoreCountry is nil because this code block doesn't work correctly in my case
`self.appStoreCountry = [(NSLocale *)[NSLocale currentLocale] objectForKey:NSLocaleCountryCode];`

I use custom Application language when run app, switching it back to System language resolves this issue
See SO answer http://stackoverflow.com/a/32569003/440465 for more details

**Comment by Abhishaker17** [comment]
Thank you for this. Switching back to System language did fix this issue. Closing.
